version: '3.7'
services:
  directus:
    image: directus/directus:latest
    expose:
      - 8055
    restart: always
    volumes:
      - directus-database:/directus/database
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
      - ./keys:/directus/keys
    env_file:
      - .env.directus
    networks:
      - vps-proxy

  storefront:
    image: ${STOREFRONT_DOCKER_IMAGE}
    expose:
      - 3000
    restart: always
    env_file:
      - .env.storefront
    networks:
      - vps-proxy

  storefront-assets:
    image: ${STOREFRONT_ASSETS_DOCKER_IMAGE}
    expose:
      - 3000
    restart: always
    networks:
      - vps-proxy

volumes:
  directus-database:
  directus-uploads:
  directus-extensions:

networks:
  vps-proxy:
    external: true
