  TopNav[m
  accueil[m
  checkout[m
  dev[m
  faq[m
  feature/inscription-page[m
  feature/newsletter[m
  feature/page-avis[m
  feature/seoArticles[m
  feature/seometadescription[m
  filtreshop[m
  fix/home-page[m
  fix/seo[m
  fix/seoSerp[m
  list[m
* [32mmain[m
  menu[m
  panier[m
  partenaire[m
  rebase[m
  refactor/aboutus-page[m
  refactor/admin-seo[m
  refactor/aide[m
  refactor/articles-cards[m
  refactor/articles-page[m
  refactor/blog[m
  refactor/easter-egg-dragproduct[m
  refactor/faq[m
  refactor/footer[m
  refactor/help-page[m
  refactor/home[m
  refactor/home-page[m
  refactor/page-help[m
  refactor/partenaires[m
  refactor/search-bar[m
  refactor/shop-disposition[m
  refactor/shop-giftcard[m
  refactor/shop-page[m
  refactor/topnav[m
  refactor/videosonvignette[m
  refactor/vignettevideos[m
  shop[m
  sortshop[m
  store[m
  topnav[m
